import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { buildSite } from "./build";
import { loadConfig } from "./config";
import type { PdfGenerator, PdfRenderOptions } from "./pipeline/renderPdf";

let dir: string;
let docs: string;

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), "monodocs-docmeta-"));
  docs = join(dir, "docs");
  await mkdir(docs, { recursive: true });
  await writeFile(join(docs, "index.md"), "# Home\n\nA line.\n");
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

/** 受け取った options を記録し canned PDF バイト列を返す偽ジェネレータ。 */
function fakePdfGenerator() {
  const calls: PdfRenderOptions[] = [];
  const gen: PdfGenerator = {
    async render(_html, options) {
      calls.push(options);
      return new TextEncoder().encode("%PDF-1.4 fake");
    },
    async close() {},
  };
  return { gen, calls };
}

async function build(name: string, config: string): Promise<string> {
  const root = join(dir, name);
  await mkdir(root, { recursive: true });
  const configFile = join(root, "monodocs.config.yml");
  await writeFile(configFile, config);
  const out = join(root, "docs.html");
  await buildSite({ inputDir: docs, configFile, outputFile: out, format: "html" });
  return readFile(out, "utf8");
}

const DOCUMENT =
  'document:\n  version: "1.2"\n  date: "2026-08-22"\n  authors:\n    - "Docs Team"\n';

describe("document.version / date / authors", () => {
  it("are accepted as written and not interpreted", async () => {
    const root = join(dir, "read");
    await mkdir(root, { recursive: true });
    const configFile = join(root, "monodocs.config.yml");
    await writeFile(configFile, DOCUMENT);
    const resolved = await loadConfig({ configFile }, dir);
    // `date` is not parsed into a calendar and `version` is not compared to anything.
    expect(resolved.documentMetadata).toEqual({
      version: "1.2",
      date: "2026-08-22",
      authors: ["Docs Team"],
    });
  });

  it("reach the footer of the generated HTML", async () => {
    const html = await build("footer", DOCUMENT);
    expect(html).toContain('<p class="document-meta">Version 1.2 · 2026-08-22 · Docs Team</p>');
    // The generator line is still there: the document's line is added beside it, not instead of it.
    expect(html).toContain("Generated by");
  });

  it("follow the document's language", async () => {
    const html = await build("footer-ja", `lang: "ja"\n${DOCUMENT}`);
    expect(html).toContain("バージョン 1.2 · 2026-08-22 · Docs Team");
  });

  it("survive branding: false, which removes monodocs' line and not the author's", async () => {
    const html = await build("no-branding", `html:\n  branding: false\n${DOCUMENT}`);
    expect(html).toContain('<p class="document-meta">Version 1.2 · 2026-08-22 · Docs Team</p>');
    // The generator line goes; the label stays in the published table, as it does today, because
    // which labels a theme uses is the theme's business.
    expect(html).not.toContain('class="document-generator"');
  });

  it("leave the footer as it was when the document says nothing", async () => {
    const html = await build("silent", "title: T\n");
    // The class name is in the stylesheet either way; what must not be there is the element.
    expect(html).not.toContain('<p class="document-meta">');
    expect(html).toContain('class="document-footer"');
    expect(html).toContain('class="document-generator"');
  });

  it("are escaped, since they come from a configuration file", async () => {
    const html = await build("escaped", 'document:\n  version: "<script>x</script>"\n');
    expect(html).not.toContain("<script>x</script>");
    expect(html).toContain("&lt;script&gt;x&lt;/script&gt;");
  });

  it("reach the PDF's Author, Subject, and Keywords", async () => {
    const { gen, calls } = fakePdfGenerator();
    const root = join(dir, "pdf");
    await mkdir(root, { recursive: true });
    const configFile = join(root, "monodocs.config.yml");
    await writeFile(configFile, DOCUMENT);
    await buildSite(
      { inputDir: docs, configFile, outputFile: join(root, "docs.pdf"), format: "pdf" },
      { pdfGenerator: gen },
    );
    expect(calls).toHaveLength(1);
    expect(calls[0]?.author).toBe("Docs Team");
    expect(calls[0]?.subject).toBe("Version 1.2 (2026-08-22)");
    expect(calls[0]?.keywords).toEqual(["1.2", "2026-08-22"]);
  });
});

describe("the build writes no date of its own", () => {
  it("produces the same bytes from the same input twice", async () => {
    // The obvious version of this feature fills the footer with the moment the build ran, and that
    // is what must not happen: a committed `docs.html` would show a diff whenever anyone rebuilt
    // it, and a reproducible build would stop being reproducible for a line nobody asked for
    // (12.4). A date in the output is a date the author wrote.
    const first = await build("repro-a", DOCUMENT);
    const second = await build("repro-b", DOCUMENT);
    expect(second).toBe(first);
    expect(first).toContain("2026-08-22");
  });
});
