import { type Diagnostic, warn } from "./diagnostics.js";
import { t } from "./messages.js";
/**
 * 生成した文書の UI ラベル（chrome）。
 *
 * 文書には一致する理由のない 2 つの言語がある。ページ本文の言語と、monodocs がその周りに
 * 被せる UI の言語である。`lang` が後者の表を選び、`html.labels` がその上に個別のエントリを
 * 差し替える。解決は core だけで行い、結果を `siteDataJson` に載せる。テーマ側（app.js）が
 * 自前の文字列を持つと、表と上書きが 2 箇所で食い違うため。
 */

/**
 * ラベルのキー集合。**1.0 で凍結される公開 API** なので、テーマがたまたま読むものに
 * 委ねず、ここで列挙して設定リファレンスに載せる。順序は文書の中での出現順に近づけてある。
 */
export const LABEL_KEYS = [
  "openSidebar",
  "closeSidebar",
  "searchPlaceholder",
  "searchLabel",
  "searchResults",
  "noResults",
  "contentWidthToggle",
  "useWideContent",
  "useStandardContent",
  "darkModeToggle",
  "tocLabel",
  "tocTitle",
  "pageNavLabel",
  "prev",
  "next",
  "wrapToggle",
  "copyCode",
  "copy",
  "copied",
  "copyFailed",
  "openImagePreview",
  "imagePreview",
  "closeImagePreview",
  "generatedBy",
  "version",
] as const;

export type LabelKey = (typeof LABEL_KEYS)[number];
export type Labels = Record<LabelKey, string>;

const EN: Labels = {
  openSidebar: "Open sidebar",
  closeSidebar: "Close sidebar",
  searchPlaceholder: "Search…",
  searchLabel: "Search documents",
  searchResults: "Search results",
  noResults: "No results",
  contentWidthToggle: "Toggle content width",
  useWideContent: "Use wide content",
  useStandardContent: "Use standard content width",
  darkModeToggle: "Toggle dark mode",
  tocLabel: "Table of contents",
  tocTitle: "On this page",
  pageNavLabel: "Page navigation",
  prev: "← Prev",
  next: "Next →",
  wrapToggle: "Toggle word wrap",
  copyCode: "Copy code",
  copy: "Copy",
  copied: "Copied!",
  copyFailed: "Copy failed",
  openImagePreview: "Open image preview",
  imagePreview: "Image preview",
  closeImagePreview: "Close image preview",
  generatedBy: "Generated by",
  version: "Version",
};

const JA: Labels = {
  openSidebar: "サイドバーを開く",
  closeSidebar: "サイドバーを閉じる",
  searchPlaceholder: "検索…",
  searchLabel: "ドキュメントを検索",
  searchResults: "検索結果",
  noResults: "該当なし",
  contentWidthToggle: "本文幅を切り替え",
  useWideContent: "本文を広く表示",
  useStandardContent: "本文を標準の幅で表示",
  darkModeToggle: "ダークモードを切り替え",
  tocLabel: "目次",
  tocTitle: "このページの内容",
  pageNavLabel: "ページ移動",
  prev: "← 前へ",
  next: "次へ →",
  wrapToggle: "折り返しを切り替え",
  copyCode: "コードをコピー",
  copy: "コピー",
  copied: "コピーしました",
  copyFailed: "コピーできませんでした",
  openImagePreview: "画像を拡大表示",
  imagePreview: "画像プレビュー",
  closeImagePreview: "画像プレビューを閉じる",
  generatedBy: "生成:",
  version: "バージョン",
};

/**
 * 同梱する表。**en と ja だけ**にとどめる。中途半端に訳した言語を core に同梱するのは、
 * その言語の読者にとって何も無いより悪く、しかも保守するのは話者ではなく維持者になる。
 * 他の言語は `html.labels` で入れられる。
 */
const TABLES: Record<string, Labels> = { en: EN, ja: JA };

export const DEFAULT_LANG = "en";

/**
 * RFC 5646 の grandfathered タグ（irregular と regular）。BCP 47 として妥当だが、
 * `Intl.getCanonicalLocales` は Unicode の locale identifier 文法で見るため大半を弾く。
 * ここで先に受けないと、`lang: i-klingon` の文書がビルドできなくなる。
 * レジストリ上は追加されない固定の集合なので、列挙で足りる。
 */
const GRANDFATHERED = new Set(
  [
    "en-GB-oed",
    "i-ami",
    "i-bnn",
    "i-default",
    "i-enochian",
    "i-hak",
    "i-klingon",
    "i-lux",
    "i-mingo",
    "i-navajo",
    "i-pwn",
    "i-tao",
    "i-tay",
    "i-tsu",
    "sgn-BE-FR",
    "sgn-BE-NL",
    "sgn-CH-DE",
    "art-lojban",
    "cel-gaulish",
    "no-bok",
    "no-nyn",
    "zh-guoyu",
    "zh-hakka",
    "zh-min",
    "zh-min-nan",
    "zh-xiang",
  ].map((tag) => tag.toLowerCase()),
);

/**
 * 構文的に妥当な BCP 47 言語タグか。
 *
 * 文書の言語であり `<html lang>` はそれを表明できなければならないので、同梱の表があるかとは
 * 無関係に「タグとして妥当か」だけを見る。妥当でない文字列は属性に書かず拒否する。
 *
 * 判定の主体は `Intl.getCanonicalLocales`（well-formed でなければ RangeError を投げる）だが、
 * これは Unicode の locale identifier 文法なので BCP 47 と完全には一致しない。妥当なのに
 * 弾かれる 2 種類 — 私用のみのタグと grandfathered タグ — を先に受ける。どちらも同梱の表は
 * 無いのでラベルは英語へ落ちるが、それは属性に書けないこととは別の話である。
 */
export function isValidLanguageTag(tag: string): boolean {
  if (tag.length === 0 || tag.length > 100) return false;
  if (GRANDFATHERED.has(tag.toLowerCase())) return true;
  // 私用のみのタグ（x-pig-latin など）。
  if (/^x(-[A-Za-z0-9]{1,8})+$/i.test(tag)) return true;
  try {
    Intl.getCanonicalLocales(tag);
    return true;
  } catch {
    return false;
  }
}

/**
 * タグから同梱の表を探すためのキー（主言語サブタグを小文字化したもの）。
 * `en-GB` / `ja-JP` / `JA` はいずれも表に行き着く。照合先の無いタグ
 * （私用のみのタグ、grandfathered タグ）は undefined を返す。
 */
function primarySubtag(tag: string): string | undefined {
  const first = tag.split("-")[0]?.toLowerCase();
  if (first === undefined || first === "" || first === "x") return undefined;
  // 主言語サブタグは 2〜3 文字（または 4〜8 文字の登録済み言語）。数字を含むものは
  // 主言語サブタグではない。
  return /^[a-z]{2,8}$/.test(first) ? first : undefined;
}

export type ResolvedLabels = {
  labels: Labels;
  /** The finding reported when no shipped table matched and English was used instead. */
  warning?: Diagnostic;
};

/**
 * `lang` に対する表を選び、`overrides` をその上に重ねる。
 *
 * 同梱の表が無いタグは拒否せず en の表へ落として警告する。拒否すると、フランス語の文書が
 * ビルドを通すためだけに自分を英語だと偽ることになり、上書きできる英語ラベルより読者にとって
 * 悪い。警告はビルド 1 回につき 1 度、タグ名を挙げて出す（呼び出し側が 1 回だけ呼ぶ）。
 */
export function resolveLabels(lang: string, overrides: Partial<Labels> = {}): ResolvedLabels {
  const key = primarySubtag(lang);
  const table = key === undefined ? undefined : TABLES[key];
  const labels = { ...(table ?? EN), ...overrides };
  if (table !== undefined) return { labels };
  return {
    labels,
    warning: warn(
      "lang/no-label-table",
      t("labels.noTable", {
        lang,
        fallback: DEFAULT_LANG,
        shipped: Object.keys(TABLES).join(", "),
      }),
    ),
  };
}
