/**
 * monodocs 自身が出すメッセージのカタログ。
 *
 * `--help`、エラー、警告のすべてがここを通る。既定は英語で、日本語は明示的に選ぶ
 * （`--lang ja` / `MONODOCS_LANG=ja`）。README・ドキュメントサイト・CONTRIBUTING・SECURITY が
 * 英語を既定に日本語を併記しているのに、CLI だけ日本語しか出さないのは、npm 経由で届く読者の
 * 大半に対して不親切だった。
 *
 * **文書の `lang`（23.4）とは別物。** あちらはビルドされるページを記述し、こちらはビルドしている
 * 端末を記述する。文書がある言語で書かれ、書いている人の端末が別の言語を返すことはよくある。
 *
 * **`LANG` / `LC_ALL` は意図的に見ない。** 自動検出は便利だが、ビルドログがどのマシンで作られたかに
 * 依存することになり、issue に貼られたログをコマンドだけからは再現できなくなる。明示指定の
 * 一度きりの手間のほうが安い。
 *
 * ## 境界
 *
 * 対象は monodocs が印字前に手にしている文字列である。依存パッケージのメッセージが包まれずに
 * そのまま利用者へ届くもの（Zod のパースエラー本体、Puppeteer のスタック）は対象外。monodocs が
 * すでに包んでいるものは、その包み側を訳す。
 */

/** 同梱するメッセージ言語。 */
export const MESSAGE_LANGS = ["en", "ja"] as const;
export type MessageLang = (typeof MESSAGE_LANGS)[number];

export const DEFAULT_MESSAGE_LANG: MessageLang = "en";

type Catalogue = Record<string, string>;

const EN = {
  // ---- config ----
  "config.parseFailed": "Failed to parse config file {path}: {detail}",
  "config.invalid": "Invalid config file {path}: {detail}",
  "config.notFound": "Config file not found: {path}",
  "config.invalidFormat": 'Invalid output format: "{value}" (expected "html", "pdf", or "both").',
  "config.invalidMaxInlineSize": "Invalid maxInlineSize: {value}",
  "config.invalidContentWidth": "Invalid contentWidth: {value}",
  "config.invalidRegexTransform": "Invalid regex transform: {detail}",
  "config.sidebarItemBothPathAndChildren":
    "sidebar.items entry must not have both path and children",
  "config.sidebarItemNeedsPathOrChildren": "sidebar.items entry needs either path or children",
  "config.sidebarItemChildrenNeedTitle": "sidebar.items entry with children needs a title",
  "config.sidebarCustomNeedsItems": 'sidebar.mode: "custom" needs sidebar.items',
  "config.sidebarItemsNeedCustom": 'sidebar.items needs sidebar.mode: "custom"',
  "config.invalidLanguageTag": "must be a syntactically valid BCP 47 language tag",
  "config.invalidPdfLengthValue":
    "must be a CSS length: a number and a unit (px, pt, mm, cm, in, rem, em), or 0",
  "config.invalidPdfLineHeightValue": "must be a positive number, without a unit",
  "config.invalidPdfCellPaddingValue": 'must be one or two CSS lengths, as in "0.3rem 0.5rem"',
  "config.invalidPdfLength": 'Invalid pdf.density {key}: "{value}" is not a CSS length.',
  "config.invalidPdfLineHeight":
    'Invalid pdf.density lineHeight: "{value}" is not a positive number.',
  "config.invalidPdfCellPadding":
    'Invalid pdf.density tableCellPadding: "{value}" is not one or two CSS lengths.',
  "config.excludeInBothPlaces":
    "Both sources.exclude and sidebar.exclude are set. Keep sources.exclude and remove sidebar.exclude.",
  "config.sidebarExcludeMoved":
    "sidebar.exclude is deprecated: use sources.exclude, which is named for what it does — a match " +
    "is left out of the bundle, not only out of the sidebar. Patterns are now added to the built-in " +
    "exclude list rather than replacing it (sources.excludeDefaults: false drops that list).",
  "config.unsupportedMessageLang":
    'Unsupported message language: "{value}" (supported: {supported}).',

  // ---- build ----
  "build.inputNotFound": "Input path not found: {path}",
  "build.inputUnsupportedFile":
    "Input file is not a supported source: {path} (supported extensions: {extensions}).",
  "build.noSources": "No Markdown / AsciiDoc files found in: {path}",
  "build.pdfImagesEmbedded":
    "Images were embedded for PDF output, overriding assets.embedImages / onLargeImage: external. " +
    "A distributed PDF cannot reach relative images outside itself.",

  // ---- pages ----
  "pages.noRenderer": 'No renderer for "{path}" ({format}); skipped.',
  "pages.routeCollision":
    'Route collision: "{route}" is generated by both "{first}" and "{second}".',
  "pages.pageIdCollision":
    'Page id collision: "{id}" is generated by both "{first}" and "{second}". Rename one of the files.',
  "pages.noTitle": 'No title found in "{path}"; using "{title}".',

  // ---- sidebar ----
  "sidebar.groupEmpty": "Sidebar group has no visible pages: {title}",
  "sidebar.itemNotFound":
    "Sidebar item not found: {path} (paths are relative to input and must resolve to a " +
    "generated page; check sources.exclude and sources.*.extensions)",
  "sidebar.itemHidden": "Sidebar item is hidden and was skipped: {path}",
  "sidebar.itemDuplicate": "Sidebar item appears more than once: {path}",
  "sidebar.notListed": "Not listed in the custom sidebar (reachable only by route): {paths}",

  // ---- themes ----
  "theme.unknown":
    'Unknown theme: {name}. Built-in themes: {builtIn}. Use a path such as "./my-theme" to load ' +
    "a custom theme directory.",
  "theme.missingTokens": "Theme template is missing required tokens ({tokens}): {source}",
  "theme.dirNotFound": "Theme directory not found: {dir}",
  "theme.notADirectory": "Theme path is not a directory: {dir}",
  "theme.empty": "Theme directory has none of {files}: {dir}",

  // ---- postprocess ----
  "post.mermaidPrerenderFailed":
    "{path}: Mermaid pre-render failed; falling back to showing the source: {detail}",
  "post.unresolvedLink": 'Unresolved link "{href}" in "{where}".',
  "post.unresolvedAnchor":
    'Unresolved anchor "#{anchor}" in "{href}"; linked to page top in "{where}".',
  "post.unsupportedImage": 'Unsupported image type "{src}" in "{path}".',
  "post.imageNotFound": 'Image not found "{src}" in "{path}".',
  "post.imageOutside": 'Image outside input directory "{src}" in "{path}"; skipped.',
  "post.imageExceedsLimit": "Image exceeds maxInlineSize: {detail}",
  "post.imageLeftAsIs": "Image too large, left as-is: {detail}",
  "post.largeImageEmbedded": "Large image embedded: {detail}",

  // ---- labels (23.4) ----
  "labels.noTable":
    'No UI label table ships for lang "{lang}"; using the {fallback} labels. Tables ship for ' +
    "{shipped}; html.labels can replace individual entries.",

  // ---- headless browser ----
  "browser.chromiumMissing":
    "A headless browser needs Chromium or Google Chrome (Microsoft Edge also works on Windows). " +
    "Set PUPPETEER_EXECUTABLE_PATH, or install Google Chrome or Chromium (for the development " +
    "Docker image, see Dockerfile.dev).",
  "browser.launchFailed": "Failed to launch the headless browser: {detail}",
  "browser.puppeteerMissingStandalone":
    "PDF output and Mermaid pre-render are unavailable in the single-executable build, which does " +
    "not bundle puppeteer-core. Use the npm build (`npm install -g monodocs`).",
  "browser.puppeteerMissing":
    "A headless browser needs puppeteer-core. The npm build installs it as an optional dependency, " +
    "so `--omit=optional` or a failed optional install is the likely cause. Reinstall with " +
    "`npm install -g monodocs`, or run `pnpm add puppeteer-core` in a development workspace.",

  // ---- PDF ----
  "pdf.pageLoadFailed": "Failed to load the page for PDF output: {detail}",
  "pdf.footerMarginTooSmall":
    "pdf.margin.bottom ({margin}) is smaller than the page-number footer needs ({needed}). The " +
    "footer is still drawn, against the paper edge — a supplied fragment does not hide itself the " +
    "way Chromium's built-in one does. Enlarge the margin, or set pdf.footer to a fragment that " +
    "fits, or pdf.footer: false to drop the band.",

  // ---- font check (24.3.3) ----
  "fontCheck.missingPdf":
    "No font on the machine running this build draws {count} character(s) this document uses, so " +
    "they come out as tofu (□ / ☒) in the PDF — permanently, in every copy of it. At risk: " +
    "{samples}. Install a font that covers them (the package that supplies one differs by " +
    "platform), or set fontCheck: off to accept it.",
  "fontCheck.missingPrerender":
    "No font on the machine running this build draws {count} character(s) used in the Mermaid " +
    "diagrams, so they come out as tofu (□ / ☒) in the SVG that mermaid.mode: pre-render bakes " +
    "into the output — in the HTML as much as in the PDF. At risk: {samples}. Install a font that " +
    "covers them (the package that supplies one differs by platform), or set fontCheck: off to " +
    "accept it.",
  "fontCheck.incomplete":
    "The font check stopped after {count} distinct characters and did not reach the end of this " +
    "document, so it found nothing rather than confirming there is nothing to find. It says so " +
    "instead of staying silent, because a check that was cut short reads exactly like one that " +
    "passed.",
  "fontCheck.sample": "{cluster} ({codepoints})",
  "fontCheck.sampleWithExample": "{cluster} ({codepoints}, e.g. {font})",
  "fontCheck.more": "and {count} more",
  "fontCheck.unusable":
    "The font check did not run: this machine draws private-use characters, which the check uses " +
    "as its reference for a missing glyph, so it cannot tell a drawn character from an undrawn " +
    "one. Nothing is reported about the fonts this build needs.",

  // ---- mermaid ----
  "mermaid.prerenderFailed": "Mermaid pre-render failed: {detail}",
  "mermaid.browserInitFailed":
    "mermaid.mode: pre-render could not initialise the browser: {detail}",
  "mermaid.prerendererMissing":
    "mermaid.mode: pre-render is set, but no pre-render renderer was supplied.",

  // ---- init (25.1) ----
  "init.exists":
    "monodocs init writes nothing when a file it would create is already there. Found: {paths}",
  // The scaffold is a document in its own right, so it follows the message language throughout —
  // comments, page text, and the `lang` it sets. A Japanese first page under `lang: "en"` would
  // be exactly the mismatch 23.4 exists to end.
  "init.configTemplate": `# monodocs configuration.
#
# Every key has a default, so this file carries only what most documents change.
# The full reference — sidebar, assets, mermaid, html, pdf, search — is at
# https://kuttsun.github.io/monodocs/docs/configuration

# Used as the document title, in <title>, and in the PDF metadata.
title: "Documentation"

# Language of the generated document. It fills <html lang> and selects the UI labels
# (the search box, "On this page", prev/next). This is not the language of monodocs'
# own messages, which is --lang / MONODOCS_LANG.
lang: "en"

# What to bundle: a directory to scan, or a single source file.
input: "./docs"

output:
  # html | pdf | both. pdf and both need Chromium on the machine running the build.
  format: "html"
  path: "./dist/docs.html"
`,
  "init.pageTemplate": `# Documentation

\`monodocs init\` wrote this page. Replace it with your own text, then add more Markdown
or AsciiDoc files next to it: every file becomes a page, and the folder structure becomes
the sidebar.

## Building

\`\`\`bash
monodocs build
\`\`\`

The result is \`dist/docs.html\`, one self-contained file — styles, images, and the search
index are all inside it — so it can be handed to someone as it is.
`,

  // ---- CLI ----
  "cli.description": "Generate a single HTML / PDF from many Markdown / AsciiDoc files",
  "cli.opt.lang": "Language of monodocs' own messages: {supported} (env: MONODOCS_LANG)",
  "cli.arg.input": "Input directory, or a single source file (default: ./docs)",
  "cli.opt.config": "Config file (default: monodocs.config.yml when present)",
  "cli.init.description": "Write a monodocs.config.yml and a first page to start from",
  "cli.created": "✓ Created {files}",
  "cli.build.description": "Build the documents into a single HTML / PDF",
  "cli.build.opt.output":
    "Output target (html: file / pdf: file / both: directory. default: ./dist/docs.html)",
  "cli.build.opt.format": "Output format html | pdf | both (default: html)",
  "cli.watch.description": "Watch the input and config file, rebuilding on change",
  "cli.watch.opt.output": "Output file (default: ./dist/docs.html)",
  "cli.serve.description": "Serve locally, watching for changes and live-reloading",
  "cli.serve.opt.port": "Port number (default: 4173)",
  "cli.serve.opt.host": "Host (default: 127.0.0.1)",
  "cli.serve.opt.open": "Open the default browser on start",
  "cli.validate.description":
    "Detect broken links, missing images, and missing titles (writes no output)",
  "cli.help.usage": "Usage:",
  "cli.help.options": "Options:",
  "cli.help.commands": "Commands:",
  "cli.help.arguments": "Arguments:",
  "cli.help.helpOption": "display help for command",
  "cli.help.helpCommand": "display help for a command",
  "cli.help.versionOption": "output the version number",
  "cli.generated": "✓ Generated {pages} page(s) -> {outputs}",
  "cli.rebuilt": "✓ Rebuilt {pages} page(s)",
  "cli.watching": "Watching for changes… (Ctrl+C to stop)",
  "cli.serving": "Serving at {url} (Ctrl+C to stop)",
  "cli.noIssues": "✓ No issues found ({pages} page(s)).",
  "cli.issues": "✗ {errors} error(s), {warnings} warning(s) in {pages} page(s).",
  "cli.browserOpenFailed": "could not open browser ({command}).",
  "cli.browserOpenFailedNoCommand": "could not open browser.",
  "cli.unknownOption": "unknown option '{value}'",
  "cli.unknownCommand": "unknown command '{value}'",
  "cli.missingArgument": "missing required argument '{value}'",
  "cli.optionMissingArgument": "option '{value}' argument missing",
  "cli.warningPrefix": "warning: {message}",
  "cli.errorPrefix": "error: {message}",
} satisfies Catalogue;

export type MessageKey = keyof typeof EN;

const JA: Record<MessageKey, string> = {
  "config.parseFailed": "設定ファイル {path} を解釈できませんでした: {detail}",
  "config.invalid": "設定ファイル {path} の内容が不正です: {detail}",
  "config.notFound": "設定ファイルが見つかりません: {path}",
  "config.invalidFormat": '出力形式が不正です: "{value}"（"html" / "pdf" / "both" のいずれか）。',
  "config.invalidMaxInlineSize": "maxInlineSize が不正です: {value}",
  "config.invalidContentWidth": "contentWidth が不正です: {value}",
  "config.invalidRegexTransform": "regex 変換が不正です: {detail}",
  "config.sidebarItemBothPathAndChildren":
    "sidebar.items の項目に path と children の両方は指定できません",
  "config.sidebarItemNeedsPathOrChildren":
    "sidebar.items の項目には path か children のどちらかが必要です",
  "config.sidebarItemChildrenNeedTitle":
    "children を持つ sidebar.items の項目には title が必要です",
  "config.sidebarCustomNeedsItems": 'sidebar.mode: "custom" には sidebar.items が必要です',
  "config.sidebarItemsNeedCustom": 'sidebar.items には sidebar.mode: "custom" が必要です',
  "config.invalidLanguageTag": "構文的に妥当な BCP 47 言語タグである必要があります",
  "config.invalidPdfLengthValue":
    "CSS の長さ（数値と単位 px / pt / mm / cm / in / rem / em、または 0）である必要があります",
  "config.invalidPdfLineHeightValue": "単位の無い正の数である必要があります",
  "config.invalidPdfCellPaddingValue":
    'CSS の長さ 1 つ、または 2 つ（"0.3rem 0.5rem" のように）である必要があります',
  "config.invalidPdfLength":
    'pdf.density の {key} が不正です: "{value}" は CSS の長さではありません。',
  "config.invalidPdfLineHeight":
    'pdf.density の lineHeight が不正です: "{value}" は正の数ではありません。',
  "config.invalidPdfCellPadding":
    'pdf.density の tableCellPadding が不正です: "{value}" は CSS の長さ 1〜2 個ではありません。',
  "config.excludeInBothPlaces":
    "sources.exclude と sidebar.exclude の両方が設定されています。" +
    "sources.exclude を残して sidebar.exclude を削除してください。",
  "config.sidebarExcludeMoved":
    "sidebar.exclude は非推奨です。sources.exclude を使ってください" +
    "（サイドバーからではなく束そのものからファイルを外す設定です）。" +
    "指定したパターンは既定の除外リストを置き換えず、そこへ追加されるようになりました" +
    "（既定リストを外すには sources.excludeDefaults: false）。",
  "config.unsupportedMessageLang": 'メッセージ言語が不正です: "{value}"（対応: {supported}）。',

  "build.inputNotFound": "入力パスが見つかりません: {path}",
  "build.inputUnsupportedFile":
    "入力ファイルの形式に対応していません: {path}（対応する拡張子: {extensions}）。",
  "build.noSources": "Markdown / AsciiDoc ファイルが見つかりません: {path}",
  "build.pdfImagesEmbedded":
    "PDF 出力のため画像を埋め込みました（assets.embedImages / onLargeImage: external を上書き）。" +
    "配布された PDF は自分の外にある相対パスの画像を参照できないためです。",

  "pages.noRenderer": '"{path}"（{format}）に対応するレンダラがありません。スキップしました。',
  "pages.routeCollision":
    'route の衝突: "{route}" が "{first}" と "{second}" の両方から生成されます。',
  "pages.pageIdCollision":
    'ページ id の衝突: "{id}" が "{first}" と "{second}" の両方から生成されます。どちらかのファイル名を変えてください。',
  "pages.noTitle": '"{path}" にタイトルがありません。"{title}" を使います。',

  "sidebar.groupEmpty": "サイドバーのグループに表示できるページがありません: {title}",
  "sidebar.itemNotFound":
    "サイドバーの項目が見つかりません: {path}（パスは入力ディレクトリ基準で、生成されるページに" +
    "解決できる必要があります。sources.exclude と sources.*.extensions を確認してください）",
  "sidebar.itemHidden": "サイドバーの項目が hidden のためスキップしました: {path}",
  "sidebar.itemDuplicate": "サイドバーの項目が重複しています: {path}",
  "sidebar.notListed": "カスタムサイドバーに未掲載です（route でのみ到達できます）: {paths}",

  "theme.unknown":
    "テーマが見つかりません: {name}。組み込みテーマ: {builtIn}。カスタムテーマを読むには " +
    '"./my-theme" のようなパスを指定してください。',
  "theme.missingTokens": "テーマのテンプレートに必要なトークンがありません（{tokens}）: {source}",
  "theme.dirNotFound": "テーマディレクトリが見つかりません: {dir}",
  "theme.notADirectory": "テーマのパスがディレクトリではありません: {dir}",
  "theme.empty": "テーマディレクトリに {files} のいずれもありません: {dir}",

  "post.mermaidPrerenderFailed":
    "{path}: Mermaid の pre-render に失敗しました（ソース表示にフォールバック）: {detail}",
  "post.unresolvedLink": 'リンクを解決できません "{href}"（"{where}"）。',
  "post.unresolvedAnchor":
    'アンカーを解決できません "#{anchor}"（"{href}"）。"{where}" ではページ先頭へリンクしました。',
  "post.unsupportedImage": '未対応の画像形式です "{src}"（"{path}"）。',
  "post.imageNotFound": '画像が見つかりません "{src}"（"{path}"）。',
  "post.imageOutside": '入力ディレクトリの外の画像です "{src}"（"{path}"）。スキップしました。',
  "post.imageExceedsLimit": "画像が maxInlineSize を超えています: {detail}",
  "post.imageLeftAsIs": "画像が大きいためそのままにしました: {detail}",
  "post.largeImageEmbedded": "大きな画像を埋め込みました: {detail}",

  "labels.noTable":
    '言語 "{lang}" 向けの UI ラベル表は同梱していません。{fallback} のラベルを使います。' +
    "同梱しているのは {shipped} です。html.labels で個別に差し替えられます。",

  "browser.chromiumMissing":
    "ヘッドレスブラウザには Chromium / Google Chrome（Windows では Microsoft Edge も可）が必要です。" +
    "PUPPETEER_EXECUTABLE_PATH を設定するか、Google Chrome もしくは Chromium をインストールしてください" +
    "（開発用 Docker では Dockerfile.dev を参照）。",
  "browser.launchFailed": "ヘッドレスブラウザの起動に失敗しました: {detail}",
  "browser.puppeteerMissingStandalone":
    "PDF 出力と Mermaid pre-render は単一実行ファイル版では利用できません" +
    "（ヘッドレスブラウザを操作する puppeteer-core を同梱していないため）。" +
    "npm 版（`npm install -g monodocs`）を使ってください。",
  "browser.puppeteerMissing":
    "ヘッドレスブラウザには puppeteer-core が必要です。npm 版では optionalDependency として " +
    "install されるため、`--omit=optional` を付けたか optional の install に失敗した可能性が" +
    "あります。`npm install -g monodocs` で入れ直すか、開発 workspace では " +
    "`pnpm add puppeteer-core` を実行してください。",

  "pdf.pageLoadFailed": "PDF 用ページの読み込みに失敗しました: {detail}",
  "pdf.footerMarginTooSmall":
    "pdf.margin.bottom（{margin}）がページ番号フッタに必要な高さ（{needed}）より小さいです。" +
    "フッタは描かれますが紙の端に貼りつきます（渡したフラグメントは Chromium 組み込みのものと" +
    "違って自分を隠しません）。余白を広げるか、pdf.footer に収まるフラグメントを指定するか、" +
    "pdf.footer: false で帯を消してください。",

  "fontCheck.missingPdf":
    "この文書が使う {count} 文字を描けるフォントが、ビルドを走らせているマシンにありません。" +
    "PDF では豆腐（□ / ☒）になります（配った複製すべてで、後からは直せません）。該当: {samples}。" +
    "それらを含むフォントを入れる（提供するパッケージ名はプラットフォームごとに違います）か、" +
    "fontCheck: off で許容してください。",
  "fontCheck.missingPrerender":
    "Mermaid の図が使う {count} 文字を描けるフォントが、ビルドを走らせているマシンにありません。" +
    "mermaid.mode: pre-render が焼き込む SVG の中で豆腐（□ / ☒）になり、PDF だけでなく HTML でも" +
    "そのままです。該当: {samples}。それらを含むフォントを入れる（提供するパッケージ名は" +
    "プラットフォームごとに違います）か、fontCheck: off で許容してください。",
  "fontCheck.incomplete":
    "フォント検査は異なる文字 {count} 個で打ち切られ、この文書の最後までは到達しませんでした。" +
    "「無かった」ではなく「そこまでは見つからなかった」という結果です。打ち切られた検査は" +
    "通過した検査とまったく同じに見えるため、黙らずにそのことを述べています。",
  "fontCheck.sample": "{cluster}（{codepoints}）",
  "fontCheck.sampleWithExample": "{cluster}（{codepoints}、例: {font}）",
  "fontCheck.more": "ほか {count} 件",
  "fontCheck.unusable":
    "フォント検査は実行しませんでした: このマシンは私用領域の文字を描画します。検査はそれを" +
    "「グリフが無い」ことの基準に使うため、描けた文字と描けなかった文字を区別できません。" +
    "このビルドが必要とするフォントについては何も報告しません。",

  "mermaid.prerenderFailed": "Mermaid の pre-render に失敗しました: {detail}",
  "mermaid.browserInitFailed": "mermaid.mode: pre-render のブラウザ初期化に失敗しました: {detail}",
  "mermaid.prerendererMissing":
    "mermaid.mode: pre-render が指定されていますが pre-render 用レンダラが渡されていません。",

  "init.exists":
    "monodocs init は、作成するファイルがすでにある場合は何も書きません。見つかったもの: {paths}",
  "init.configTemplate": `# monodocs の設定ファイル。
#
# すべてのキーに既定値があるため、ここには変更することの多いものだけを書いてあります。
# 全キーの一覧（sidebar / assets / mermaid / html / pdf / search など）は
# https://kuttsun.github.io/monodocs/ja/docs/configuration

# 文書のタイトル。<title> と PDF のメタデータにも使われます。
title: "ドキュメント"

# 生成される文書の言語。<html lang> に入り、UI ラベル（検索ボックス、「このページの内容」、
# 前後ナビ）の表を選びます。monodocs 自身のメッセージの言語（--lang / MONODOCS_LANG）とは
# 別の設定です。
lang: "ja"

# 束ねる対象。走査するディレクトリ、または単一のソースファイル。
input: "./docs"

output:
  # html | pdf | both。pdf と both はビルドするマシンに Chromium が必要です。
  format: "html"
  path: "./dist/docs.html"
`,
  "init.pageTemplate": `# ドキュメント

このページは \`monodocs init\` が書きました。内容を書き換え、Markdown や AsciiDoc の
ファイルを隣に足していってください。1 ファイルが 1 ページになり、フォルダ構成が
そのままサイドバーになります。

## ビルド

\`\`\`bash
monodocs build
\`\`\`

出力は \`dist/docs.html\` の 1 ファイルです。スタイルも画像も検索インデックスも中に
入っているので、そのまま渡せます。
`,

  "cli.description": "複数の Markdown / AsciiDoc から単一 HTML / PDF を生成する",
  "cli.opt.lang": "monodocs 自身のメッセージの言語: {supported}（環境変数: MONODOCS_LANG）",
  "cli.arg.input": "入力ディレクトリ、または単一のソースファイル（既定: ./docs）",
  "cli.opt.config": "設定ファイル（既定: monodocs.config.yml があれば使用）",
  "cli.init.description": "monodocs.config.yml と最初のページを書き出す",
  "cli.created": "✓ {files} を作成しました",
  "cli.build.description": "ドキュメントをビルドして単一 HTML / PDF を生成する",
  "cli.build.opt.output":
    "出力先（html: ファイル / pdf: ファイル / both: ディレクトリ。既定: ./dist/docs.html）",
  "cli.build.opt.format": "出力形式 html | pdf | both（既定: html）",
  "cli.watch.description": "入力・設定ファイルの変更を監視して再ビルドする",
  "cli.watch.opt.output": "出力ファイル（既定: ./dist/docs.html）",
  "cli.serve.description": "ローカルサーバーで配信し、変更を監視してライブリロードする",
  "cli.serve.opt.port": "ポート番号（既定: 4173）",
  "cli.serve.opt.host": "ホスト（既定: 127.0.0.1）",
  "cli.serve.opt.open": "起動時に既定のブラウザで開く",
  "cli.validate.description":
    "リンク切れ・画像欠落・タイトル欠落などを検出する（出力は書き出さない）",
  "cli.help.usage": "使い方:",
  "cli.help.options": "オプション:",
  "cli.help.commands": "コマンド:",
  "cli.help.arguments": "引数:",
  "cli.help.helpOption": "このコマンドのヘルプを表示する",
  "cli.help.helpCommand": "コマンドのヘルプを表示する",
  "cli.help.versionOption": "バージョンを表示する",
  "cli.generated": "✓ {pages} ページを生成しました -> {outputs}",
  "cli.rebuilt": "✓ {pages} ページを再生成しました",
  "cli.watching": "変更を監視しています… (Ctrl+C で停止)",
  "cli.serving": "{url} で配信しています (Ctrl+C で停止)",
  "cli.noIssues": "✓ 問題は見つかりませんでした（{pages} ページ）。",
  "cli.issues": "✗ エラー {errors} 件、警告 {warnings} 件（{pages} ページ）。",
  "cli.browserOpenFailed": "ブラウザを開けませんでした（{command}）。",
  "cli.browserOpenFailedNoCommand": "ブラウザを開けませんでした。",
  "cli.unknownOption": "不明なオプションです '{value}'",
  "cli.unknownCommand": "不明なコマンドです '{value}'",
  "cli.missingArgument": "必須の引数がありません '{value}'",
  "cli.optionMissingArgument": "オプション '{value}' に値がありません",
  "cli.warningPrefix": "warning: {message}",
  "cli.errorPrefix": "error: {message}",
};

const CATALOGUES: Record<MessageLang, Record<MessageKey, string>> = { en: EN, ja: JA };

let current: MessageLang = DEFAULT_MESSAGE_LANG;

/**
 * 以降のメッセージの言語を決める。CLI が起動時に 1 度だけ呼ぶ。
 * ライブラリとして使う場合は呼ばなければ英語のままになる。
 */
export function setMessageLang(lang: MessageLang): void {
  current = lang;
}

export function getMessageLang(): MessageLang {
  return current;
}

/**
 * `--lang` と `MONODOCS_LANG` から言語を決める。フラグ > 環境変数 > 既定。
 * 対応しない値は、黙ってフォールバックせず対応する値を挙げて拒否する（指定したのに効いていない、
 * という最も気づきにくい失敗にしない）。
 */
export function resolveMessageLang(options: { flag?: string; env?: string }): MessageLang {
  // フラグは「無い」と「空で指定された」を区別する。空を既定へ落とすと、`--lang=` が
  // 環境変数まで打ち消したうえで黙って英語になり、優先順位も未対応値の拒否も破れる。
  // 環境変数の空文字は「未設定」として扱う（シェルではそれが通例）。
  const value = options.flag ?? (options.env === "" ? undefined : options.env);
  if (value === undefined) return DEFAULT_MESSAGE_LANG;
  const found = MESSAGE_LANGS.find((lang) => lang === value.toLowerCase());
  if (found) return found;
  // ここだけは翻訳前に出す必要がある（どの言語を使うかを決めている最中なので）。
  throw new Error(
    format(EN["config.unsupportedMessageLang"], {
      value,
      supported: MESSAGE_LANGS.join(", "),
    }),
  );
}

/** `{name}` を差し替える。値が無いプレースホルダはそのまま残す（消すと文が壊れる）。 */
function format(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match,
  );
}

/** 現在の言語でメッセージを組み立てる。 */
export function t(key: MessageKey, params: Record<string, string | number> = {}): string {
  return format(CATALOGUES[current][key], params);
}

/** テストと、カタログの網羅性検査のために公開する。 */
export const MESSAGE_KEYS = Object.keys(EN) as MessageKey[];
