#!/usr/bin/env bash
#
# Generate the PDF sample pages shown in the top README.
#
# Builds the short sample document in site/samples/readme to a PDF and turns three of its sheets
# into images as they are, adding only a border: the cover, the table of contents, and the page with
# the formulas. The cover and the printed table of contents are enabled by the monodocs.config.yml
# next to the sources (read from the input directory); the footer is the default page number.
# GitHub renders the README, so the images are committed.
#
#   site/samples/readme -> docs/assets/pdf-sample-cover.png, pdf-sample-toc.png, pdf-sample-math.png
#
# Formulas need an OpenType MATH font, which the dev image deliberately lacks (the font-check tests
# rely on a machine without one). The vendored Latin Modern Math is loaded for this build only, and
# fontCheck: error stops the build if it is still missing.
#
# The end of the body carries "Generated by monodocs vX.Y.Z", so regenerate after each release.
#
# Usage:
#   scripts/app.sh pnpm build && scripts/readme-pdf-sample.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/scripts/app.sh"

WORK="$ROOT/tmp/readme-pdf-sample"
rm -rf "$WORK"
mkdir -p "$WORK"

# app.sh runs in /work/app with HOME=/tmp, which is discarded after each run. fontconfig picks up
# ~/.fonts, so the font exists for this one run and nowhere else.
# The single quotes are deliberate: $HOME must expand inside the container, not here.
# shellcheck disable=SC2016
"$APP" sh -c '
  set -e
  mkdir -p "$HOME/.fonts"
  cp packages/core/test-fixtures/fonts/lm-math/opentype/latinmodern-math.otf "$HOME/.fonts/"
  node packages/cli/dist/index.js build ../site/samples/readme \
    -f pdf -o ../tmp/readme-pdf-sample/sample.pdf
'

# The cover is sheet 1 and the table of contents sheet 2. The formula page is the first sheet with a
# sentence from its body (its headings are listed in the table of contents too, so they cannot mark it).
# shellcheck disable=SC2016 # the script runs inside the container, where its variables expand
if ! math_page="$("$APP" sh -c '
  pdf=../tmp/readme-pdf-sample/sample.pdf
  pages=$(pdfinfo "$pdf" | sed -n "s/^Pages: *//p")
  for p in $(seq 3 "$pages"); do
    if pdftotext -f "$p" -l "$p" "$pdf" - | grep -q "is held by gravity"; then
      echo "$p"
      exit 0
    fi
  done
  exit 1
')"; then
  echo "[readme-pdf-sample] no page contains \"is held by gravity\" (site/samples/readme/math.md)" >&2
  exit 1
fi

# A white sheet disappears into GitHub's light background, so add a border (scripts/frame-ppm.mjs).
shot() {
  "$APP" pdftoppm -f "$1" -l "$1" -singlefile -scale-to-x 600 -scale-to-y -1 \
    ../tmp/readme-pdf-sample/sample.pdf "../tmp/readme-pdf-sample/$2"
  "$APP" node ../scripts/frame-ppm.mjs \
    "../tmp/readme-pdf-sample/$2.ppm" "../docs/assets/pdf-sample-$2.png"
}
shot 1 cover
shot 2 toc
shot "$math_page" math

rm -rf "$WORK"
echo "[readme-pdf-sample] docs/assets/pdf-sample-{cover,toc,math}.png (math: page $math_page)"
