import type { Page, SourceFile, SourceRenderer } from "../types.js";
import { toPageId, toRoute } from "../route.js";

export type BuildPagesResult = {
  pages: Page[];
  warnings: string[];
};

/** ファイル名（拡張子除く）からタイトルを導出する。 */
function deriveTitleFromPath(relativePath: string): string {
  const base = relativePath.split("/").pop() ?? relativePath;
  const name = base.replace(/\.[^.]+$/, "");
  return name === "index" ? "Home" : name;
}

/**
 * ソースファイル群を renderer で処理し、共通の Page モデルへ正規化する。
 * route の重複はエラー、タイトル欠落は警告とする。
 */
export async function buildPages(
  sources: SourceFile[],
  renderers: SourceRenderer[],
): Promise<BuildPagesResult> {
  const rendererByFormat = new Map(renderers.map((r) => [r.format, r]));
  const pages: Page[] = [];
  const warnings: string[] = [];
  const seenRoutes = new Map<string, string>();
  const seenPageIds = new Map<string, string>();

  for (const source of sources) {
    const renderer = rendererByFormat.get(source.format);
    if (!renderer) {
      warnings.push(`No renderer for "${source.relativePath}" (${source.format}); skipped.`);
      continue;
    }

    const route = toRoute(source.relativePath);
    const id = toPageId(route);

    const existing = seenRoutes.get(route);
    if (existing) {
      throw new Error(
        `Route collision: "${route}" is generated by both "${existing}" and "${source.relativePath}".`,
      );
    }
    seenRoutes.set(route, source.relativePath);

    // route が異なっても page id が衝突しうる（例: "a-b.md" と "a/b.md" は
    // どちらも "a-b"）。見出し ID prefix の衝突を防ぐため検知してエラーにする。
    const existingPageId = seenPageIds.get(id);
    if (existingPageId) {
      throw new Error(
        `Page id collision: "${id}" is generated by both "${existingPageId}" and "${source.relativePath}". Rename one of the files.`,
      );
    }
    seenPageIds.set(id, source.relativePath);

    const meta = await renderer.extractMeta(source);
    const rendered = await renderer.render(source, {
      page: { id, route, relativePath: source.relativePath, format: source.format },
    });

    const title = meta.title?.trim() || deriveTitleFromPath(source.relativePath);
    if (!meta.title) {
      warnings.push(`No title found in "${source.relativePath}"; using "${title}".`);
    }

    pages.push({
      id,
      route,
      sourcePath: source.absolutePath,
      relativePath: source.relativePath,
      format: source.format,
      title,
      order: meta.order,
      hidden: meta.hidden,
      description: meta.description,
      rawSource: source.raw,
      html: rendered.html,
      text: rendered.text,
      headings: rendered.headings,
      links: rendered.links,
      assets: rendered.assets,
    });
  }

  // order（明示順）→ route の順に並べる。
  pages.sort((a, b) => {
    const ao = a.order ?? Number.MAX_SAFE_INTEGER;
    const bo = b.order ?? Number.MAX_SAFE_INTEGER;
    if (ao !== bo) return ao - bo;
    return a.route.localeCompare(b.route);
  });

  return { pages, warnings };
}
